import { Card } from './types';

export const CARD_BACK_IMAGE = 'https://qualisartifex1.github.io/Tarot-Readings/tarotcardback.png'

const IMAGE_BASE_URL = 'https://www.sacred-texts.com/tarot/pkt/img';

export const TAROT_DECK: Card[] = [
  // Major Arcana
  { name: 'The Fool', image: `${IMAGE_BASE_URL}/ar00.jpg`, type: 'major' },
  { name: 'The Magician', image: `${IMAGE_BASE_URL}/ar01.jpg`, type: 'major' },
  { name: 'The High Priestess', image: `${IMAGE_BASE_URL}/ar02.jpg`, type: 'major' },
  { name: 'The Empress', image: `${IMAGE_BASE_URL}/ar03.jpg`, type: 'major' },
  { name: 'The Emperor', image: `${IMAGE_BASE_URL}/ar04.jpg`, type: 'major' },
  { name: 'The Hierophant', image: `${IMAGE_BASE_URL}/ar05.jpg`, type: 'major' },
  { name: 'The Lovers', image: `${IMAGE_BASE_URL}/ar06.jpg`, type: 'major' },
  { name: 'The Chariot', image: `${IMAGE_BASE_URL}/ar07.jpg`, type: 'major' },
  { name: 'Strength', image: `${IMAGE_BASE_URL}/ar08.jpg`, type: 'major' },
  { name: 'The Hermit', image: `${IMAGE_BASE_URL}/ar09.jpg`, type: 'major' },
  { name: 'Wheel of Fortune', image: `${IMAGE_BASE_URL}/ar10.jpg`, type: 'major' },
  { name: 'Justice', image: `${IMAGE_BASE_URL}/ar11.jpg`, type: 'major' },
  { name: 'The Hanged Man', image: `${IMAGE_BASE_URL}/ar12.jpg`, type: 'major' },
  { name: 'Death', image: `${IMAGE_BASE_URL}/ar13.jpg`, type: 'major' },
  { name: 'Temperance', image: `${IMAGE_BASE_URL}/ar14.jpg`, type: 'major' },
  { name: 'The Devil', image: `${IMAGE_BASE_URL}/ar15.jpg`, type: 'major' },
  { name: 'The Tower', image: `${IMAGE_BASE_URL}/ar16.jpg`, type: 'major' },
  { name: 'The Star', image: `${IMAGE_BASE_URL}/ar17.jpg`, type: 'major' },
  { name: 'The Moon', image: `${IMAGE_BASE_URL}/ar18.jpg`, type: 'major' },
  { name: 'The Sun', image: `${IMAGE_BASE_URL}/ar19.jpg`, type: 'major' },
  { name: 'Judgement', image: `${IMAGE_BASE_URL}/ar20.jpg`, type: 'major' },
  { name: 'The World', image: `${IMAGE_BASE_URL}/ar21.jpg`, type: 'major' },
  // Wands
  { name: 'Ace of Wands', image: `${IMAGE_BASE_URL}/waac.jpg`, type: 'minor' },
  { name: 'Two of Wands', image: `${IMAGE_BASE_URL}/wa02.jpg`, type: 'minor' },
  { name: 'Three of Wands', image: `${IMAGE_BASE_URL}/wa03.jpg`, type: 'minor' },
  { name: 'Four of Wands', image: `${IMAGE_BASE_URL}/wa04.jpg`, type: 'minor' },
  { name: 'Five of Wands', image: `${IMAGE_BASE_URL}/wa05.jpg`, type: 'minor' },
  { name: 'Six of Wands', image: `${IMAGE_BASE_URL}/wa06.jpg`, type: 'minor' },
  { name: 'Seven of Wands', image: `${IMAGE_BASE_URL}/wa07.jpg`, type: 'minor' },
  { name: 'Eight of Wands', image: `${IMAGE_BASE_URL}/wa08.jpg`, type: 'minor' },
  { name: 'Nine of Wands', image: `${IMAGE_BASE_URL}/wa09.jpg`, type: 'minor' },
  { name: 'Ten of Wands', image: `${IMAGE_BASE_URL}/wa10.jpg`, type: 'minor' },
  { name: 'Page of Wands', image: `${IMAGE_BASE_URL}/wapa.jpg`, type: 'minor' },
  { name: 'Knight of Wands', image: `${IMAGE_BASE_URL}/wakn.jpg`, type: 'minor' },
  { name: 'Queen of Wands', image: `${IMAGE_BASE_URL}/waqu.jpg`, type: 'minor' },
  { name: 'King of Wands', image: `${IMAGE_BASE_URL}/waki.jpg`, type: 'minor' },
  // Cups
  { name: 'Ace of Cups', image: `${IMAGE_BASE_URL}/cuac.jpg`, type: 'minor' },
  { name: 'Two of Cups', image: `${IMAGE_BASE_URL}/cu02.jpg`, type: 'minor' },
  { name: 'Three of Cups', image: `${IMAGE_BASE_URL}/cu03.jpg`, type: 'minor' },
  { name: 'Four of Cups', image: `${IMAGE_BASE_URL}/cu04.jpg`, type: 'minor' },
  { name: 'Five of Cups', image: `${IMAGE_BASE_URL}/cu05.jpg`, type: 'minor' },
  { name: 'Six of Cups', image: `${IMAGE_BASE_URL}/cu06.jpg`, type: 'minor' },
  { name: 'Seven of Cups', image: `${IMAGE_BASE_URL}/cu07.jpg`, type: 'minor' },
  { name: 'Eight of Cups', image: `${IMAGE_BASE_URL}/cu08.jpg`, type: 'minor' },
  { name: 'Nine of Cups', image: `${IMAGE_BASE_URL}/cu09.jpg`, type: 'minor' },
  { name: 'Ten of Cups', image: `${IMAGE_BASE_URL}/cu10.jpg`, type: 'minor' },
  { name: 'Page of Cups', image: `${IMAGE_BASE_URL}/cupa.jpg`, type: 'minor' },
  { name: 'Knight of Cups', image: `${IMAGE_BASE_URL}/cukn.jpg`, type: 'minor' },
  { name: 'Queen of Cups', image: `${IMAGE_BASE_URL}/cuqu.jpg`, type: 'minor' },
  { name: 'King of Cups', image: `${IMAGE_BASE_URL}/cuki.jpg`, type: 'minor' },
  // Swords
  { name: 'Ace of Swords', image: `${IMAGE_BASE_URL}/swac.jpg`, type: 'minor' },
  { name: 'Two of Swords', image: `${IMAGE_BASE_URL}/sw02.jpg`, type: 'minor' },
  { name: 'Three of Swords', image: `${IMAGE_BASE_URL}/sw03.jpg`, type: 'minor' },
  { name: 'Four of Swords', image: `${IMAGE_BASE_URL}/sw04.jpg`, type: 'minor' },
  { name: 'Five of Swords', image: `${IMAGE_BASE_URL}/sw05.jpg`, type: 'minor' },
  { name: 'Six of Swords', image: `${IMAGE_BASE_URL}/sw06.jpg`, type: 'minor' },
  { name: 'Seven of Swords', image: `${IMAGE_BASE_URL}/sw07.jpg`, type: 'minor' },
  { name: 'Eight of Swords', image: `${IMAGE_BASE_URL}/sw08.jpg`, type: 'minor' },
  { name: 'Nine of Swords', image: `${IMAGE_BASE_URL}/sw09.jpg`, type: 'minor' },
  { name: 'Ten of Swords', image: `${IMAGE_BASE_URL}/sw10.jpg`, type: 'minor' },
  { name: 'Page of Swords', image: `${IMAGE_BASE_URL}/swpa.jpg`, type: 'minor' },
  { name: 'Knight of Swords', image: `${IMAGE_BASE_URL}/swkn.jpg`, type: 'minor' },
  { name: 'Queen of Swords', image: `${IMAGE_BASE_URL}/swqu.jpg`, type: 'minor' },
  { name: 'King of Swords', image: `${IMAGE_BASE_URL}/swki.jpg`, type: 'minor' },
  // Pentacles
  { name: 'Ace of Pentacles', image: `${IMAGE_BASE_URL}/peac.jpg`, type: 'minor' },
  { name: 'Two of Pentacles', image: `${IMAGE_BASE_URL}/pe02.jpg`, type: 'minor' },
  { name: 'Three of Pentacles', image: `${IMAGE_BASE_URL}/pe03.jpg`, type: 'minor' },
  { name: 'Four of Pentacles', image: `${IMAGE_BASE_URL}/pe04.jpg`, type: 'minor' },
  { name: 'Five of Pentacles', image: `${IMAGE_BASE_URL}/pe05.jpg`, type: 'minor' },
  { name: 'Six of Pentacles', image: `${IMAGE_BASE_URL}/pe06.jpg`, type: 'minor' },
  { name: 'Seven of Pentacles', image: `${IMAGE_BASE_URL}/pe07.jpg`, type: 'minor' },
  { name: 'Eight of Pentacles', image: `${IMAGE_BASE_URL}/pe08.jpg`, type: 'minor' },
  { name: 'Nine of Pentacles', image: `${IMAGE_BASE_URL}/pe09.jpg`, type: 'minor' },
  { name: 'Ten of Pentacles', image: `${IMAGE_BASE_URL}/pe10.jpg`, type: 'minor' },
  { name: 'Page of Pentacles', image: `${IMAGE_BASE_URL}/pepa.jpg`, type: 'minor' },
  { name: 'Knight of Pentacles', image: `${IMAGE_BASE_URL}/pekn.jpg`, type: 'minor' },
  { name: 'Queen of Pentacles', image: `${IMAGE_BASE_URL}/pequ.jpg`, type: 'minor' },
  { name: 'King of Pentacles', image: `${IMAGE_BASE_URL}/peki.jpg`, type: 'minor' },
];