
import { Card } from './types';

const IMAGE_BASE_URL = 'https://www.sacred-texts.com/tarot/pkt/img';

export const TAROT_DECK: Card[] = [
  // Major Arcana
  { name: 'The Fool', image: `${IMAGE_BASE_URL}/ar00.jpg` },
  { name: 'The Magician', image: `${IMAGE_BASE_URL}/ar01.jpg` },
  { name: 'The High Priestess', image: `${IMAGE_BASE_URL}/ar02.jpg` },
  { name: 'The Empress', image: `${IMAGE_BASE_URL}/ar03.jpg` },
  { name: 'The Emperor', image: `${IMAGE_BASE_URL}/ar04.jpg` },
  { name: 'The Hierophant', image: `${IMAGE_BASE_URL}/ar05.jpg` },
  { name: 'The Lovers', image: `${IMAGE_BASE_URL}/ar06.jpg` },
  { name: 'The Chariot', image: `${IMAGE_BASE_URL}/ar07.jpg` },
  { name: 'Strength', image: `${IMAGE_BASE_URL}/ar08.jpg` },
  { name: 'The Hermit', image: `${IMAGE_BASE_URL}/ar09.jpg` },
  { name: 'Wheel of Fortune', image: `${IMAGE_BASE_URL}/ar10.jpg` },
  { name: 'Justice', image: `${IMAGE_BASE_URL}/ar11.jpg` },
  { name: 'The Hanged Man', image: `${IMAGE_BASE_URL}/ar12.jpg` },
  { name: 'Death', image: `${IMAGE_BASE_URL}/ar13.jpg` },
  { name: 'Temperance', image: `${IMAGE_BASE_URL}/ar14.jpg` },
  { name: 'The Devil', image: `${IMAGE_BASE_URL}/ar15.jpg` },
  { name: 'The Tower', image: `${IMAGE_BASE_URL}/ar16.jpg` },
  { name: 'The Star', image: `${IMAGE_BASE_URL}/ar17.jpg` },
  { name: 'The Moon', image: `${IMAGE_BASE_URL}/ar18.jpg` },
  { name: 'The Sun', image: `${IMAGE_BASE_URL}/ar19.jpg` },
  { name: 'Judgement', image: `${IMAGE_BASE_URL}/ar20.jpg` },
  { name: 'The World', image: `${IMAGE_BASE_URL}/ar21.jpg` },
  // Wands
  { name: 'Ace of Wands', image: `${IMAGE_BASE_URL}/waac.jpg` },
  { name: 'Two of Wands', image: `${IMAGE_BASE_URL}/wa02.jpg` },
  { name: 'Three of Wands', image: `${IMAGE_BASE_URL}/wa03.jpg` },
  { name: 'Four of Wands', image: `${IMAGE_BASE_URL}/wa04.jpg` },
  { name: 'Five of Wands', image: `${IMAGE_BASE_URL}/wa05.jpg` },
  { name: 'Six of Wands', image: `${IMAGE_BASE_URL}/wa06.jpg` },
  { name: 'Seven of Wands', image: `${IMAGE_BASE_URL}/wa07.jpg` },
  { name: 'Eight of Wands', image: `${IMAGE_BASE_URL}/wa08.jpg` },
  { name: 'Nine of Wands', image: `${IMAGE_BASE_URL}/wa09.jpg` },
  { name: 'Ten of Wands', image: `${IMAGE_BASE_URL}/wa10.jpg` },
  { name: 'Page of Wands', image: `${IMAGE_BASE_URL}/wapa.jpg` },
  { name: 'Knight of Wands', image: `${IMAGE_BASE_URL}/wakn.jpg` },
  { name: 'Queen of Wands', image: `${IMAGE_BASE_URL}/waqu.jpg` },
  { name: 'King of Wands', image: `${IMAGE_BASE_URL}/waki.jpg` },
  // Cups
  { name: 'Ace of Cups', image: `${IMAGE_BASE_URL}/cuac.jpg` },
  { name: 'Two of Cups', image: `${IMAGE_BASE_URL}/cu02.jpg` },
  { name: 'Three of Cups', image: `${IMAGE_BASE_URL}/cu03.jpg` },
  { name: 'Four of Cups', image: `${IMAGE_BASE_URL}/cu04.jpg` },
  { name: 'Five of Cups', image: `${IMAGE_BASE_URL}/cu05.jpg` },
  { name: 'Six of Cups', image: `${IMAGE_BASE_URL}/cu06.jpg` },
  { name: 'Seven of Cups', image: `${IMAGE_BASE_URL}/cu07.jpg` },
  { name: 'Eight of Cups', image: `${IMAGE_BASE_URL}/cu08.jpg` },
  { name: 'Nine of Cups', image: `${IMAGE_BASE_URL}/cu09.jpg` },
  { name: 'Ten of Cups', image: `${IMAGE_BASE_URL}/cu10.jpg` },
  { name: 'Page of Cups', image: `${IMAGE_BASE_URL}/cupa.jpg` },
  { name: 'Knight of Cups', image: `${IMAGE_BASE_URL}/cukn.jpg` },
  { name: 'Queen of Cups', image: `${IMAGE_BASE_URL}/cuqu.jpg` },
  { name: 'King of Cups', image: `${IMAGE_BASE_URL}/cuki.jpg` },
  // Swords
  { name: 'Ace of Swords', image: `${IMAGE_BASE_URL}/swac.jpg` },
  { name: 'Two of Swords', image: `${IMAGE_BASE_URL}/sw02.jpg` },
  { name: 'Three of Swords', image: `${IMAGE_BASE_URL}/sw03.jpg` },
  { name: 'Four of Swords', image: `${IMAGE_BASE_URL}/sw04.jpg` },
  { name: 'Five of Swords', image: `${IMAGE_BASE_URL}/sw05.jpg` },
  { name: 'Six of Swords', image: `${IMAGE_BASE_URL}/sw06.jpg` },
  { name: 'Seven of Swords', image: `${IMAGE_BASE_URL}/sw07.jpg` },
  { name: 'Eight of Swords', image: `${IMAGE_BASE_URL}/sw08.jpg` },
  { name: 'Nine of Swords', image: `${IMAGE_BASE_URL}/sw09.jpg` },
  { name: 'Ten of Swords', image: `${IMAGE_BASE_URL}/sw10.jpg` },
  { name: 'Page of Swords', image: `${IMAGE_BASE_URL}/swpa.jpg` },
  { name: 'Knight of Swords', image: `${IMAGE_BASE_URL}/swkn.jpg` },
  { name: 'Queen of Swords', image: `${IMAGE_BASE_URL}/swqu.jpg` },
  { name: 'King of Swords', image: `${IMAGE_BASE_URL}/swki.jpg` },
  // Pentacles
  { name: 'Ace of Pentacles', image: `${IMAGE_BASE_URL}/peac.jpg` },
  { name: 'Two of Pentacles', image: `${IMAGE_BASE_URL}/pe02.jpg` },
  { name: 'Three of Pentacles', image: `${IMAGE_BASE_URL}/pe03.jpg` },
  { name: 'Four of Pentacles', image: `${IMAGE_BASE_URL}/pe04.jpg` },
  { name: 'Five of Pentacles', image: `${IMAGE_BASE_URL}/pe05.jpg` },
  { name: 'Six of Pentacles', image: `${IMAGE_BASE_URL}/pe06.jpg` },
  { name: 'Seven of Pentacles', image: `${IMAGE_BASE_URL}/pe07.jpg` },
  { name: 'Eight of Pentacles', image: `${IMAGE_BASE_URL}/pe08.jpg` },
  { name: 'Nine of Pentacles', image: `${IMAGE_BASE_URL}/pe09.jpg` },
  { name: 'Ten of Pentacles', image: `${IMAGE_BASE_URL}/pe10.jpg` },
  { name: 'Page of Pentacles', image: `${IMAGE_BASE_URL}/pepa.jpg` },
  { name: 'Knight of Pentacles', image: `${IMAGE_BASE_URL}/pekn.jpg` },
  { name: 'Queen of Pentacles', image: `${IMAGE_BASE_URL}/pequ.jpg` },
  { name: 'King of Pentacles', image: `${IMAGE_BASE_URL}/peki.jpg` },
];
